version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: on-failure
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data:
